### ISSUE TITLE
GOBIN sets incorrect directory.

### ISSUE THREAD

**Issue by grawlinson** [tockins/realize#1]
Realize installs binaries to `$GOPATHbin` instead of `$GOPATH/bin`

[Relevant code](https://github.com/tockins/realize/blob/6ba882a03d38c40ff25bc97947613bf1000ba06a/realize/project.go#L105)

Missing a slash there, I think. I found ~/gobin/ on my computer and was wondering where it came from.

**Comment by Asoseil** [comment]
thanks for the tip. it should be fixed now
