### ISSUE TITLE
Can not recognize the default $GOPATH 

### ISSUE THREAD

**Issue by mingrammer** [tockins/realize#102]
I'm using the `GOPATH` as default one of Go 1.9: `~/go`. And all go commands is working correctly without any problems. But, when I run the `realize start`, the realize throws the `$GOPATH isn't set properly` error.

It seems like that the realize can not recognize the default `GOPATH`. Is it a bug?

**Comment by mingrammer** [comment]
Of course, If I set the `GOPATH` manually, It works. But, It is little a bit trivial.

**Comment by Asoseil** [comment]
Is there a way to discover gopath if it'snt exported?

**Comment by Asoseil** [comment]
Realize works with gopath that you can see using "go env"

**Comment by Asoseil** [comment]
Starting from go 1.8, the GOPATH environment variable now has a default value if it is unset. It defaults to $HOME/go on Unix and %USERPROFILE%/go on Windows

**Comment by mingrammer** [comment]
@Asoseil Yes the `go env` shows `GOPATH` correctly as `$HOME/go`.

After Go 1.8, We able to get the `GOPATH` from `go/build` builtin package by `build.Default.GOPATH`.

So, I may be able to contribute to resolve this issue.

**Comment by Asoseil** [comment]
Ok great thanks

**Comment by mingrammer** [comment]
@Asoseil I've sent a PR :)
