### ISSUE TITLE
Multiple projects do not work. Always watches/runs last defined project.

### ISSUE THREAD

**Issue by hishamk** [tockins/realize#109]
Under the new config format (schema), adding another section -name:<project name> will result in only that project being run and watch. Any other projects defined above it will not be watched nor run.

Additionally, for projects which are defined above the last project, trying realize start --name="<project name>" does not work as Realize errors with: [15:41:43][REALIZE] : there is no project with the given name

However, trying to remove <project name> works:
[REALIZE] : Your project was successfully removed

On examining the code it seems that duplicates is the culprit:
Duplicates check projects with same name or same combinations of main/path

This would be a loss of functionality for me as I usually have one binary and I run it twice under different arguments as it is composed of two distinct functionalities. I.e. a fat binary that acts as a server or a client, depending on the args provided. Considering it a duplicate since it is basically the same path makes this impossible. The older config style did not have this issue.

**Comment by Asoseil** [comment]
I just published a revision of the version 1.5.1. With this new release, there are no more checks on duplicate paths but only on duplicate names. On fresh-example you can find an example configuration for multiple projects

**Comment by conventi** [comment]
@hishamk Could you provide us your config file?

**Comment by hishamk** [comment]
settings:
  legacy:
    force: false
    interval: 10s
server:
  status: false
  open: false
  host: localhost
  port: 5001
schema:
- name: game
  path: .
  commands:
    run: true
  args:
  - startserver
  watcher:
    preview: true
    paths:
    - ./src/
    - ./cmd/
    extensions:
    - go
    ignored_paths:
    - .git
    - .realize
    - vendor/
    - .wercker/
    - .idea/
    - .glide/
    - tmp/
    - k8s/
    - log/
    - db/
    - config/
    - build/
    - bin/
- name: game
  path: .
  commands:
    run: true
  args:
  - startclient
  watcher:
    paths:
    - ./src/
    - ./cmd/
    extensions:
    - go
    ignored_paths:
    - .git
    - .realize
    - vendor/
    - .wercker/
    - .idea/
    - .glide/
    - tmp/
    - k8s/
    - log/
    - db/
    - config/
    - build/
    - bin/

**Comment by hishamk** [comment]
For now, on my fork I've modified duplicate and removed:
		if value.Path == val.Path {
			return val, errors.New("There is already a project with path '" + val.Path + "'. Check your config file!")
		}

**Comment by Asoseil** [comment]
Could you try with the last version? This behavior should be already fixed

**Comment by Asoseil** [comment]
Should be fixed with v1.5.2
