### ISSUE TITLE
performance issues

### ISSUE THREAD

**Issue by dashaus** [tockins/realize#12]
Any error occurs now, but the performance has been decreased a lot. It occurs before that `realize` begins to install and run the project.

`realize` counts 895 files 304 folders in my project so I think to not be noticed in small projects.

**Comment by conventi** [comment]
@dashaus can you try with `--no-fmt` flag or the equivalent `app_fmt: false` in realize.config.yaml?

**Comment by dashaus** [comment]
Ok. This solved the problem but when I do a change in a file, `realize` displays this and nothing more:
```
[20:38:02][MONOCULUM] : /Users/emilio/go/src/monoculum/init.go
```

**Comment by conventi** [comment]
@dashaus ok thanks! The test that I've ask you to do is only for debugging. The performance issue is a regress of `realize` and so a bug. Now we have to investigate in the latests commits and we will fix as soon as possible.

**Comment by conventi** [comment]
@dashaus can you confirm that this issue is appeared only after latest commits? Thanks in advice for you collaboration!

**Comment by dashaus** [comment]
yes.

**Comment by Asoseil** [comment]
we have moved in the goroutines each initial gofmt
