### ISSUE TITLE
realize 1.5.2 does not trigger on file changes

### ISSUE THREAD

**Issue by llonchj** [tockins/realize#126]
OS: MacOS High Sierra (10.13.1)
go1.9.2 darwin/amd64

realize 1.5.1 works fine

**Comment by Asoseil** [comment]
Should be fixed, I was using v1.5.1 and i didn't see the problem, thanks

**Comment by Asoseil** [comment]
I'll add another fix for this behevior in next hours

**Comment by llonchj** [comment]
Thanks!
