### ISSUE TITLE
Use realize on self

### ISSUE THREAD

**Issue by philoserf** [tockins/realize#129]
What better example can there be than using a tool upon the tool itself.

**Comment by Asoseil** [comment]
We already use realize for itself, so we will surely insert a paragraph about that

**Comment by philoserf** [comment]
There isn't any` .realize` directory in the repo so, that it is used here, is not available for others to see.

**Comment by conventi** [comment]
Hi @philoserf, you are right! We will commit it in next release (for sure we close this issue when we have done)!

**Comment by Asoseil** [comment]
moved to 2.1

**Comment by philoserf** [comment]
🥇
