### ISSUE TITLE
Clarifying the documentation

### ISSUE THREAD

**Issue by chmike** [tockins/realize#13]
> From project/projects root execute:

What is this `project/projects` directory ? 

Does Realize run a daemon that detects file changes ? If yes, how is the daemon started ?

**Comment by chmike** [comment]
Sorry for my last question. My bad. Realize is run manually by executing the command `realize run` in its own shell so that its output can be analysed. This tool is pretty handy. 

The colours have apparently a particular meaning. I would be interested to know more about their meaning.

**Comment by Asoseil** [comment]
we are going to do a docs about the colors value
