### ISSUE TITLE
Crash in windows

### ISSUE THREAD

**Issue by thanhps42** [tockins/realize#132]
I got crash when realize reload 3-4 times.
I use: realize start --run

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x82baae]

goroutine 6 [running]:
main.(*Project).walk(0xc042134000, 0xc042177dc0, 0x3f, 0x0, 0x0, 0xb88460, 0xc04215f560, 0xc04215f560, 0xc042177de9)
        D:/Workspace/src/github.com/tockins/realize/watcher.go:404 +0x2ce
main.(*Project).(main.walk)-fm(0xc042177dc0, 0x3f, 0x0, 0x0, 0xb88460, 0xc04215f560, 0x0, 0x0)
        D:/Workspace/src/github.com/tockins/realize/watcher.go:103 +0x70
path/filepath.walk(0xc0421ef380, 0x28, 0xb90120, 0xc042268d20, 0xc042031cd8, 0x0, 0x3)
        C:/Go/src/path/filepath/path.go:377 +0x2f2
path/filepath.Walk(0xc0421ef380, 0x28, 0xc042031cd8, 0xc042268cc0, 0x0)
        C:/Go/src/path/filepath/path.go:403 +0x124
main.(*Project).watch(0xc042134000)
        D:/Workspace/src/github.com/tockins/realize/watcher.go:149 +0x11e8
created by main.(*realize).run
        D:/Workspace/src/github.com/tockins/realize/cmd.go:126 +0x2b8

**Comment by Asoseil** [comment]
Hi, we are working to fix windows with next version 2.0

**Comment by Asoseil** [comment]
#19
