### ISSUE TITLE
Logs and fmt not displayed

### ISSUE THREAD

**Issue by amirkheirabadi** [tockins/realize#138]
when I use `realize` no anybody of my logs displayed.
how can I solve this?

**Comment by Asoseil** [comment]
Are you using a standard log.Print or fmt.Print? 
Do you have this problem even with a simple script that prints text?

**Comment by amirkheirabadi** [comment]
yes, I use standard log, fmt .
I don't have any problem when using simple `go install ` and etc but when I use realize even with simple script don't display any log and fmt

**Comment by conventi** [comment]
Hi @amirkheirabadi, could you give us some informations about your working environment (OS, realize version, etc) and a code block with the print statement?

**Comment by amirkheirabadi** [comment]
sorry, I think found the problem. this problem happened when I use Echo framework :)
now, how can I solve this?

**Comment by conventi** [comment]
I think that echo framework use an external library to print logs and errors. `realize` support standard golang log functions so probably you have to change logs statements (but I cannot give you a final answer). Let me know if you resolve the issue and for sure we are here for any questions!

**Comment by Asoseil** [comment]
This isn't a problem related to realize, third part print methods can't be supported

**Comment by darurats** [comment]
I got same issue here, use fmt and log default. Anyone can help how to solve this or how to to output log in a file?
