### ISSUE TITLE
Error with simple program

### ISSUE THREAD

**Issue by chmike** [tockins/realize#14]
Realize run display me this error. This occurs when there are some compilation errors. 
In this case compilation errors are not always shown by realize.

```
[13:44:52][SIMPLEFILESYNC] : /home/meessen/Sources/go/src/simpleFileSync/main.go
[13:44:52][SIMPLEFILESYNC] There are some errors in  /home/meessen/Sources/go/src/simpleFileSync/main.go :
/home/meessen/Sources/go/src/simpleFileSync/main.go:1:1: expected ';', found 'EOF'
/home/meessen/Sources/go/src/simpleFileSync/main.go:1:1: expected 'IDENT', found 'EOF'
/home/meessen/Sources/go/src/simpleFileSync/main.go:1:1: expected 'package', found 'EOF'

exit status 2
```

**Comment by conventi** [comment]
@chmike a `realize` run the `gofmt`tool for checking errors in projects. `gofmt` analyze the source code and return all the syntax errors but no the errors related to the import statements. Did you have this behavior?

**Comment by Asoseil** [comment]
the reported bug was an output of the gofmt check
