### ISSUE TITLE
--run parameters do not work

### ISSUE THREAD

**Issue by korovaisdead** [tockins/realize#148]
`realize start --path="/print/printer" --run print/cmd/main.go --no-config`

This command still tries to execute main.go from the project root directory.

**Comment by Asoseil** [comment]
try using realize start --path="print/printer" --run --no-config
with /print/printer you are searching under ~/print/printer

**Comment by korovaisdead** [comment]
sorry, my fault, the command I'm running is:
`realize start --path="/go/src/gihub.com/blablabla/print/printer" --run print/cmd/main.go --no-config`
Anyway, your answer doesn't seem to be valid because it won't help me to run exactly the  `./cmd/main.go` 


your command will search for the go files in the root directory, which is the path directory: `print/printer`.

So from my side the label `invalid` is wrong for the ticket.

**Comment by Asoseil** [comment]
you can't add a value to run using the command line, only by config
i'll try to test as soon as possible using a realize config file

**Comment by Asoseil** [comment]
but what's the use case and your tree?
- print
-- printer
-- cmd 
do you want to watch for printer dir and at each change do you want to run cmd?

**Comment by korovaisdead** [comment]
That was just an example. So I will describe the issue:
tree:
./  
--./cmd
----./microservice1
----./microservice2
----./microservice1
--./some-dir
--./some-dir-with-static-shit
--./etc

During the development, I usually create the docker-compose setup to work with microservices as they are in the staging environment. 

From my side, it looks like I can run each microservice in its own container with `-v` attached directory with the `realize start ...` inside it running as a `CMD` in order to reload each microservice independently. It works ok while I do only need the main.go file inside the project root directory. But if I have the tons of executables inside my project it completely impossible to run realize for each of them. (btw the ./cmd/app1; ./cmd/app2; ./cmd/app3 structure is quite popular in the go world). 

So one more time: I can't watch one directory (root `./` for example) while running the go file from the `./cmd/something` directory.

**Comment by Asoseil** [comment]
This is a question that we have already discussed on gitter. In go each dir is a different project, this is the logic of the language, so in realize you should define a project for each dir.
You can set a custom run only for build files, if you use install (default option with run) realize will search under gobin.
Anyway you can solve using a trick like this, putting the config in the dir that you would like to run:
`  watcher:
    paths:
    - /
    - ./..
`

**Comment by Asoseil** [comment]
check this example https://github.com/tockins/realize-examples/tree/master/multiple
