### ISSUE TITLE
Cannot disable installl

### ISSUE THREAD

**Issue by raja** [tockins/realize#158]
I cannot disable the install of a binary. I simply want to go run main.go with the supplied arguments. Everything is working fine but I want to disable installing the binary in the go path bin directory.

I have tried setting the status to false for install in the the yaml config as well as removing it entirely. Neither seems to work. Here is the config:

settings:
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 0
  host: ""
schema:
- name: APPNAME
  path: .
  commands:
    vet:
      status: false
    test:
      status: false
    run:
      status: true
    install:
      status: false
  args:
  - server
  watcher:
    paths:
    - /
    extensions:
    - go
    - info
    - banner
    ignored_paths:
    - .git
    - .realize
    - vendor

**Comment by Asoseil** [comment]
you should remove the run option. How would you execute your program without an install or a build?

**Comment by meowgorithm** [comment]
I second this. I’m hoping to simply perform a `go run [paths]`, and re-run that command after files changed. Possible?

**Comment by Asoseil** [comment]
you can do this with realize start --run (use install to compile by default) but at each file change, you need to recompile your program using install or build.
