### ISSUE TITLE
Allow alternate ways to build code

### ISSUE THREAD

**Issue by lucsky** [tockins/realize#16]
Right now `realize` wraps and calls the `go` tool to build code, which is a sensible and obvious default. However, it might be good to allow people who use emerging alternate ways of building Go code to use `realize` as well (I'm specifically thinking about [GB](http://getgb.io) here).

**Comment by Asoseil** [comment]
I don't know well the tool. i will check it in the next days

**Comment by lucsky** [comment]
I mentioned `GB` as an example but my initial thought was rather about providing a generic way to allow custom building/running/testing commands. Sorry for not being clear enough.

**Comment by Asoseil** [comment]
#69
