### ISSUE TITLE
Why not add `--legacy` option to `realize start` instead of specified in .realize.yaml file

### ISSUE THREAD

**Issue by DarthPestilane** [tockins/realize#160]
Consider it as a suggestion. 

Sometimes we want to do `realize start --nc --run` in a container of docker. But when we modify the code, realize won't detect the change, thanks to the [limitations of fsnotify#55](https://github.com/tockins/realize/issues/55). So we have to specify using legacy watch in `.realize.yaml` file.

Realize is a wonderful tool for golang development. I'm wondering whether realize can support `realize start --legacy` option in order to specify using legacy watch but without a config file. 

Thanks.

**Comment by Asoseil** [comment]
yeah it seems a good idea, i'll add this suggestion to next realese. 1 second by default could be ok?

**Comment by shane151** [comment]
Please update the docs/README.md for this option.

I didn't realise it existed until I found this issue.
