### ISSUE TITLE
No longer installable

### ISSUE THREAD

**Issue by grncdr** [tockins/realize#24]
Install has broken with labstack/echo moving to v3 in their master branch. `go get github.com/tockins/realize` gives the following error:

```
package github.com/labstack/echo/engine/standard: cannot find package "github.com/labstack/echo/engine/standard" in any of:
  ... (from $GOROOT)
  ... (from $GOPATH)
```

It seems like vendoring this dependency might be appropriate.

**Comment by Asoseil** [comment]
#25

**Comment by Asoseil** [comment]
maybe we could add a dependencies file, such as glide or godep. any other ideas to resolve these issues with external packages?

**Comment by grncdr** [comment]
IMO the only sane way to handle external deps right now is vendoring yourself, either by copying sources or using git submodules. Requiring users to use glide or godep is a bit off-putting.

Another option would be publishing cross-compiled binaries from CI, which would let you manage your dependencies however you like and allowing users the simplest possible install.

**Comment by Asoseil** [comment]
everything should work with go get
