### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by geddski** [tockins/realize#26]
`go get github.com/tockins/realize`

causes this error:

# github.com/tockins/realize/server
../../github.com/tockins/realize/server/main.go:88: e.Start undefined (type *echo.Echo has no field or method Start)
../../github.com/tockins/realize/server/main.go:129: cannot use c.Response() (type engine.Response) as type http.ResponseWriter in argument to websocket.Handler(func literal).ServeHTTP:
        engine.Response does not implement http.ResponseWriter (wrong type for Header method)
                have Header() engine.Header
                want Header() http.Header
../../github.com/tockins/realize/server/main.go:129: http.Request.Body is a field, not a method
../../github.com/tockins/realize/server/main.go:129: cannot use c.Request() (type engine.Request) as type *http.Request in argument to websocket.Handler(func literal).ServeHTTP

**Comment by Asoseil** [comment]
strange, i cleaned my src folder and launched "go get realize" but i haven't any errors (tried with go 1.7).
> go get github.com/tockins/realize/...

**Comment by hpsoar** [comment]
I too encountered this error, and fixed by updating module `echo`.

**Comment by Asoseil** [comment]
for the end of this month i should be able to release the new version of realize with the dependencies updated. Sorry for the delay, I will try to fix this bug as soon as possible
