### ISSUE TITLE
How can I contribute?

### ISSUE THREAD

**Issue by vmesel** [tockins/realize#3]
Im a programmer who wants to contribute with this project! What could I do to start making code for realize?

**Comment by conventi** [comment]
Thanks for asking! We are defining the roadmap of the project and the medium-long term goals. Next week we will be released the first stable version and we will start the development of new features.

**Comment by vmesel** [comment]
When you guys decide what to do, ill be a contributor!

**Comment by conventi** [comment]
In this week we are evaluating all the things and after we will comunicate: for now we thank you again!

**Comment by conventi** [comment]
@vmesel I close this issue because I think that is better to use [Gitter](https://gitter.im/tockins/realize) for this questions! I've already posted an answer in the dedicated `realize` channel.
