### ISSUE TITLE
run: true requires bin:true?!

### ISSUE THREAD

**Issue by KEANO3** [tockins/realize#31]
Why do you need to install the binary to $GOPATH/bin if build is true? Just use the binary inside the project

**Comment by Asoseil** [comment]
I think it could be implemented without problems. I'll verify as soon as possible

**Comment by KEANO3** [comment]
Without looking into the code: Should be pretty easy. Instead of invoking just {projectname} prepend it with the project path and append the parameters. voila

Or if it's not possible at least throw an error/warning/info if somebody uses "realize add --no-bin --build" without "--no-run" to prevent confusion why the tool isn't running at all
