### ISSUE TITLE
Make listen port configurable

### ISSUE THREAD

**Issue by serussell** [tockins/realize#37]
The listen port is currently hard coded to 5001.  This can cause conflicts with other services.  While this can be worked around in the main HTTP server by changing the port in the source code, the websockets are also hard-coded in Javascript to connect over 5001.  This is more of a problem because the assets are encoded as bin data but are not included in the repository, and so can't be edited & re-generated.  As a result, `realize` is not runnable on any machine where port 5001 is unavailable.

A solution would be to:

1. Make the listen port configurable via a `--port` option to the `run` command.
2. Pass the port in to `all.min.js` (the embedded bin data asset responsible for setting up the web socket) via the generated index, and have the websocket connection code use the variable.

**Comment by Asoseil** [comment]
#38

**Comment by serussell** [comment]
Awesome quick response.  However, the new build now returns bin data on http request:

```
1002)~ % curl -i https://USER:PASS@MYDOMAIN
HTTP/1.1 200 OK
Content-Length: 421
Content-Type: text/html; charset=utf-8
Date: Wed, 21 Dec 2016 02:09:54 GMT
Vary: Accept-Encoding

�       n����Kk�      4Q�7�>H�Yo rT%j��|T�  uF]P��V��T^7B@��Cʢ�KQ0�ꤷޓ��HBv��L�<Pkd̳��G3n��U]oR��)m=\�jn���^!�1c�Kc�
                                                                                                                  c�+c��f9xQ^���/ � ��g�"�gg��
]�*�"*@Q+�4��12*�L�(H���7��z:   _O�����|%                                                                                                                                                     
```

**Comment by serussell** [comment]
@Asoseil should I file this as a different ticket?  Would you regenerate the assets?

Thanks.

**Comment by serussell** [comment]
@Asoseil This may be a problem with my set-up.  Hold on.
