### ISSUE TITLE
Dosen't work with a mounted volume to a Docker container

### ISSUE THREAD

**Issue by Crizstian** [tockins/realize#44]
Doesnt detect the changes from the outside of the container, but it detects the changes inside the container.

This is the command inside the Dockerfile

CMD [ "realize", "run", "main.go"]

---

This is my comand to start the container

docker run --name easycast-go -p 8080:8080 --link easycast-db:db -e DB_LINK='yes' -v "$(PWD)/src":/go/src/easycast/src -d easycast-go

**Comment by Asoseil** [comment]
can you try with the develop branch and with the legacy watch option?

**Comment by Crizstian** [comment]
It works with this options in the Dockerfile

CMD [ "realize", "run", "--legacy", "--no-config", "--server", "--no-install"]

thanks seems that legacy works better with docker mount volumes

**Comment by phamdt** [comment]
had to make this change to make @Crizstian 's  example work:
`CMD [ "realize", "start", "--legacy", "--no-config", "--server"]`
