### ISSUE TITLE
style.go fails to build

### ISSUE THREAD

**Issue by joeblew99** [tockins/realize#52]
osx, go 1.8.1

````
go get github.com/tockins/realize
# github.com/tockins/realize/style
src/github.com/tockins/realize/style/style.go:10: color.New(color.Attribute(s)).Sprint undefined (type *color.Color has no field or method Sprint)
src/github.com/tockins/realize/style/style.go:14: color.New(color.Attribute(s), color.Bold).Sprint undefined (type *color.Color has no field or method Sprint)

````

i tried a go get -u- -v also but did not help.

**Comment by Asoseil** [comment]
There is a dependencies to upgrade (fatih/color to version 1.4.1). We have added the support to dep  dependencies management for solve this kind of issue. Maybe you can also solve with a go get github.com/tockins/realize/... or removing the folder "fatith/color" from your src directory.

**Comment by joeblew99** [comment]
i use dep now, but there is no .toml in the git repo.
```
/Users/apple/workspace/go/src/github.com/tockins/realize
x-MacBook-Pro:realize apple$ ls
LICENSE		README.md	lock.json	manifest.json	realize.go	server		settings	style		watcher
x-MacBook-Pro:realize apple$ dep status
could not find project Gopkg.toml, use dep init to initiate a manifest
x-MacBook-Pro:realize apple$ 

```

i tried both but none worked.
think the best way is to start usng dep

**Comment by joeblew99** [comment]
@Asoseil works for me. thanks !
