### ISSUE TITLE
Support custom build paths

### ISSUE THREAD

**Issue by dovys** [tockins/realize#53]
Hi guys, is there a way to define custom build paths without initializing the config?
What I'm trying to do: `realize run --path svc/ --no-install --no-config`
I want it to watch the `svc/`, but build the `svc/cmd/svc/main.go`

My project tree:
```
svc/
─ cmd
  └── svc
      └── main.go
─ service.go
─ service_test.go
```

Thanks :)

**Comment by dovys** [comment]
Also is there a way to pass the config file as an argument? On the github page there are docs for a `realize fast` command which seems to be the only one to allow passing in a config, but it isn't available in the actual release.

**Comment by Asoseil** [comment]
The idea is to keep the main options by command line. The fast command was removed because there was a lot of options to manage. For a not standard configuration we suggest to use the config file.

**Comment by yaegashi** [comment]
Hi, I have a similar project tree, how can I write the config file to build/test/run `svc/cmd/svc` sub directory while watching the whole `svc` directory?  Is it actually possible?
