### ISSUE TITLE
FsNotify does not detect changes inside container running in Kubernetes pod

### ISSUE THREAD

**Issue by hishamk** [tockins/realize#55]
Setup:
1 - Create a golang container to build and run your app.
2- Run it through a Minikube Kubernetes cluster pod. Map the dirs to the host machine to enable editing of source.

Test:
1- Editing source on host machine and saving does not trigger a realize re-build. Yes, it is the same file in the pod and the change does happen.

2- Using kubectl to start a terminal session inside pod and editing/creating files WILL trigger a realize re-build.

On the other hand, using Docker and mapping the host drive and changing files on the host does trigger realize re-build - so it does work in a Docker environment, but not in a Kubernetes pod environment.

Workaround:
Using legacy file watching with realize startup options does enable it to work.

**Comment by Asoseil** [comment]
Inside a container only work the legacy watch. it isn't a realize problem but a limitations of fsnotify.
> File notifications have a tendency of not working across shares (NFS, Vagrant mounts)

**Comment by HunnTeRUS** [comment]
The event that we receive when the config changed is the REMOVE event. Then, you can use this (example in GoLang):
```
if event.Op == fsnotify.Remove {\n
	     // remove the watcher
	     watcher.Remove(event.Name)
	     // add a new watcher pointing to the new symlink/file
	     watcher.Add(configfile)
	     reloadConfig()
}
// also allow normal files to be modified and reloaded.
if event.Op&fsnotify.Write == fsnotify.Write {
	reloadConfig()
}
```
