### ISSUE TITLE
realize:: command not found

### ISSUE THREAD

**Issue by k0fi** [tockins/realize#67]
I can not run it:

> > me@pc:~/go/src/myapp$ realize init
> > realize: command not found
> 
> > me@pc:~/go/src/myapp$ realize: command not found
> > realize:: command not found
> 
> > me@pc:~/go/src/myapp$ go env
> > GOARCH="amd64"
> > GOBIN=""
> > GOEXE=""
> > GOHOSTARCH="amd64"
> > GOHOSTOS="linux"
> > GOOS="linux"
> > GOPATH="/home/me/go"
> > GORACE=""
> > GOROOT="/usr/lib/go-1.6"
> > GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
> > GO15VENDOREXPERIMENT="1"
> > CC="gcc"
> > GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
> > CXX="g++"
> > CGO_ENABLED="1"
> 
How can I fix this?

**Comment by Asoseil** [comment]
Do you have Realize in your go/bin?
