### ISSUE TITLE
print by log package is not displayed in terminal. It Is a behavior expected?

### ISSUE THREAD

**Issue by dashaus** [tockins/realize#8]
```go

import (
    "fmt"
    "log"
)

func main() {
    fmt.Println("IT IS DISPLAYED IN THE TERMINAL")
    log.Println("BUT IT IS NOT DISPLAYED IN THE TERMINAL")
}

```

**Comment by dashaus** [comment]
By the way, this package is fucking more quickly that fresh. Congratulations! I love it! 👍

**Comment by vmesel** [comment]
I think this is not a question for the package, try going on the #go-nuts irc and chat with them! This is a GoLang doubt not a package one! Sorry for being sort of rude.

**Comment by dashaus** [comment]
I mean, when you run the code by "go run main.go" both are displayed but with `realized` not. So I think that the question is related to this package, not with Go.

**Comment by conventi** [comment]
@vmesel I'm afraid that @dashaus is in right. We have to make some test before give a final response but I'm pretty sure that the bug is related to the output streams(only stdout) of projects that realize scan and print.

**Comment by vmesel** [comment]
So lets try to test it down! Again, sorry for being rude! But actually, the log class shouldnt output just in the logger instance? Should it be printed in another part of the program?

**Comment by conventi** [comment]
We have to scan and print all the output for projects that are under watching. We think that this is the best approach and so the best solution but if you have some suggestione we can evaluate.

**Comment by dashaus** [comment]
Without place to doubt, I think that `realize` should be transparent in that and leave it to provision of the developer where want to print, if in terminal or another place.

**Comment by conventi** [comment]
@dashaus obviously! We have to evaluate how can configure this and what alternatives provide.

**Comment by braindev** [comment]
@dashaus FWIW you can get the log output to show up if you add:

```go
log.SetOutput(os.Stdout)
```

I tried to figure out why the logging is disconnected from stdout but I haven't succeeded yet.

**Comment by dashaus** [comment]
@braindev Thanks you!
