### ISSUE TITLE
flags not passed to go app

### ISSUE THREAD

**Issue by dhax** [tockins/realize#81]
Hi,
I have a flag defined in my go app which works fine when starting with go run main.go --debug.
But I am not able to set it at the end of realize run command like
```
realize run --debug
// or
realize run --test --debug
```
output is always: flag provided but not defined: -debug
Am I doing something wrong, should it work this way according to the readme?
Version is 1.4.1 on OS X

**Comment by Asoseil** [comment]
Is already fixed in dev branch, i'll update the master to v1.4.2 this weekend

**Comment by dhax** [comment]
ahh cool, thanks for instant reply ;)

**Comment by Asoseil** [comment]
i just remastered a new 1.4.1 version without the bugs
