### ISSUE TITLE
not waiting for the file to get written completely

### ISSUE THREAD

**Issue by aliforever** [tockins/realize#87]
Hi.
Realize is running in a server and I'm working on the files in my computer, then upload them to the server.
The problem is that the upload takes up to a second, which causes the error:
`funcs/engine.go:1:1: expected 'package', found 'EOF'`

I have to upload the file again immediately, sometimes 3 times in a row. Are there any solutions?

**Comment by Asoseil** [comment]
i'll try to replicate this bug and fix it in the next version

**Comment by Asoseil** [comment]
it's really hard to fix properly, there is no event that notify this behavior. The problem isn't strictly related to upload but is generated by the series of process related to file writing

**Comment by Asoseil** [comment]
#94
