### ISSUE TITLE
build tags

### ISSUE THREAD

**Issue by marwan-at-work** [tockins/realize#91]
i can't seem to find a way to have realize build my source code with particular flags. Such as 
`go build -tags !linux` 

Did I miss the documentation or is this not currently possible?

**Comment by Asoseil** [comment]
what's your argument? 
may you try with --yourArg or using config file.
Check this example https://github.com/tockins/realize-examples/tree/master/args

**Comment by marwan-at-work** [comment]
@Asoseil the problem is that my `build` process has its own args that are different from my `run` process. 
Here is what I do manually:

`go build -tags 'mytag'` 

`./my-binary -myFlag=myValue`

**Comment by Asoseil** [comment]
#94 solved, there is an example in realize examples repo
